matches:
  # Rich text Jira link
  - trigger: ":rtj"
    markdown: "{{link}}"
    vars:
      - name: clipboard
        type: clipboard
      - name: link
        type: shell
        params:
          cmd: node "$CONFIG/match/packages/jira-links/script.mjs" '{{clipboard}}'

  # Markdown Jira link
  - trigger: ":mdj"
    replace: "{{link}}"
    vars:
      - name: clipboard
        type: clipboard
      - name: link
        type: shell
        params:
          cmd: node "$CONFIG/match/packages/jira-links/script.mjs" '{{clipboard}}'

  # TODO: HTML Jira link
